-- CREAMOS LA BASE DE DATOS
CREATE DATABASE prueba;

-- USAMOS LA BASE DE DATOS DE usuarios
use prueba;

-- CREANDO LA TABLA 
CREATE TABLE usuarios (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL
);

-- MOSTRAR LAS TABLAS DE LA BD 
SHOW TABLES;

-- INSERTAR UN REGISTRO EN LA BD
INSERT INTO usuarios (name, password) 
VALUES('Guillermo', 'memo1234');

-- DESCRIBIR LA TABLA
DESCRIBE usuarios;

-- SELECCIONAR DATOS DE LA TABLA USUARIOS
SELECT * FROM usuarios;